#pragma once

#include "sdk/interfaces.h"
#include "sdk/netvars.h"

#define SEQ_DEFAULT_DRAW			0
#define SEQ_DEFAULT_IDLE1			1
#define SEQ_DEFAULT_IDLE2			2
#define SEQ_DEFAULT_LIGHT_MISS1		3
#define SEQ_DEFAULT_LIGHT_MISS2		4
#define SEQ_DEFAULT_LIGHT_HIT1		5
#define SEQ_DEFAULT_LIGHT_HIT2		6
#define SEQ_DEFAULT_LIGHT_BSTAB1	7
#define SEQ_DEFAULT_LIGHT_BSTAB2	8
#define SEQ_DEFAULT_HEAVY_MISS1		9
#define SEQ_DEFAULT_HEAVY_HIT1		10
#define SEQ_DEFAULT_HEAVY_BSTAB1	11
#define SEQ_DEFAULT_LOOKAT01		12

#define SEQ_BUTTERFLY_DRAW1			0
#define SEQ_BUTTERFLY_DRAW2			1
#define SEQ_BUTTERFLY_LOOKAT01		13
#define SEQ_BUTTERFLY_LOOKAT03		15

enum EEconItemQuality
{
	AE_UNDEFINED = -1,

	AE_NORMAL = 0,
	AE_GENUINE = 1,
	AE_VINTAGE,
	AE_UNUSUAL,
	AE_UNIQUE,
	AE_COMMUNITY,
	AE_DEVELOPER,
	AE_SELFMADE,
	AE_CUSTOMIZED,
	AE_STRANGE,
	AE_COMPLETED,
	AE_HAUNTED,
	AE_TOURNAMENT,
	AE_FAVORED,

	AE_MAX_TYPES,
};

enum ItemDefinitionIndex : short
{
	WEAPON_INVALID = -1,
	WEAPON_DEAGLE = 1,
	WEAPON_ELITE,
	WEAPON_FIVESEVEN,
	WEAPON_GLOCK,
	WEAPON_AK47 = 7,
	WEAPON_AUG,
	WEAPON_AWP,
	WEAPON_FAMAS,
	WEAPON_G3SG1,
	WEAPON_GALILAR = 13,
	WEAPON_M249,
	WEAPON_M4A1 = 16,
	WEAPON_MAC10,
	WEAPON_P90 = 19,
	WEAPON_MP5 = 23,
	WEAPON_UMP45,
	WEAPON_XM1014,
	WEAPON_BIZON,
	WEAPON_MAG7,
	WEAPON_NEGEV,
	WEAPON_SAWEDOFF,
	WEAPON_TEC9,
	WEAPON_TASER,
	WEAPON_HKP2000,
	WEAPON_MP7,
	WEAPON_MP9,
	WEAPON_NOVA,
	WEAPON_P250,
	WEAPON_SHIELD,
	WEAPON_SCAR20,
	WEAPON_SG556,
	WEAPON_SSG08,
	WEAPON_KNIFEGG,
	WEAPON_KNIFE,
	WEAPON_FLASHBANG,
	WEAPON_HEGRENADE,
	WEAPON_SMOKEGRENADE,
	WEAPON_MOLOTOV,
	WEAPON_DECOY,
	WEAPON_INCGRENADE,
	WEAPON_C4,
	WEAPON_HEALTHSHOT = 57,
	WEAPON_KNIFE_T = 59,
	WEAPON_M4A1_SILENCER,
	WEAPON_USP_SILENCER,
	WEAPON_CZ75A = 63,
	WEAPON_REVOLVER,
	WEAPON_TAGRENADE = 68,
	WEAPON_FISTS,
	WEAPON_BREACHCHARGE,
	WEAPON_TABLET = 72,
	WEAPON_MELEE = 74,
	WEAPON_AXE,
	WEAPON_HAMMER,
	WEAPON_SPANNER = 78,
	WEAPON_KNIFE_GHOST = 80,
	WEAPON_FIREBOMB,
	WEAPON_DIVERSION,
	WEAPON_FRAG_GRENADE,
	WEAPON_SNOWBALL,
	WEAPON_BUMPMINE,
	WEAPON_BAYONET = 500,
	WEAPON_KNIFE_FLIP = 505,
	WEAPON_KNIFE_GUT,
	WEAPON_KNIFE_KARAMBIT,
	WEAPON_KNIFE_M9_BAYONET,
	WEAPON_KNIFE_TACTICAL,
	WEAPON_KNIFE_FALCHION = 512,
	WEAPON_KNIFE_SURVIVAL_BOWIE = 514,
	WEAPON_KNIFE_BUTTERFLY,
	WEAPON_KNIFE_PUSH,
	WEAPON_KNIFE_URSUS = 519,
	WEAPON_KNIFE_GYPSY_JACKKNIFE,
	WEAPON_KNIFE_STILETTO = 522,
	WEAPON_KNIFE_WIDOWMAKER,
	GLOVE_STUDDED_BLOODHOUND = 5027,
	GLOVE_T_SIDE = 5028,
	GLOVE_CT_SIDE = 5029,
	GLOVE_SPORTY = 5030,
	GLOVE_SLICK = 5031,
	GLOVE_LEATHER_WRAP = 5032,
	GLOVE_MOTORCYCLE = 5033,
	GLOVE_SPECIALIST = 5034,
	GLOVE_HYDRA = 5035
};

struct SkinChange
{
	ItemDefinitionIndex itemIndex = WEAPON_INVALID; // Used for changing knife models
	float itemWear = 0.00001f;	// Float val 0 - 1 for setting wear
	int seed = 0; // Seed for pattern based skins
	int quality = AE_NORMAL; // Set weapon prefix
	int paintKit = 0; // Skin paintkit id
	int statTrakKills = -1; // Number of stattrak kills (TODO: Currently stattrak will show user unknown - look into this)
};

namespace SkinChanger
{
	void OnFramePostDataUpdateStart();

	extern RecvProxyFn ogRecvProxy_nModelIndex;
	void RecvProxy_nModelIndex(const CRecvProxyData* pData, void* pStruct, void* pOut);

	extern RecvProxyFn ogRecvProxy_nSequence;
	void RecvProxy_nSequence(const CRecvProxyData* pData, void* pStruct, void* pOut);

	void DumpModelIndices();

	void LoadSkinChanges();
}